import "server-only";

/**
 * Every string on the public hub, resolved once per request from the
 * `web_marketing` bundle and handed down as plain props.
 *
 * One place, because the page is a server component that owns the
 * translator and the interactive parts are client components that must not
 * ship a second i18n bundle to a page that should stay light. A section
 * takes the slice it needs.
 *
 * Copy the AGENT configured (a headline, a service name) is not here: that
 * comes from their document and wins over these defaults wherever it is set.
 */

type T = (key: string, opts?: { ns?: string; [k: string]: unknown }) => string;

export function hubLabels(t: T) {
  const h = (key: string, vars?: Record<string, unknown>) =>
    t(`hub.${key}`, { ns: "web_marketing", ...(vars ?? {}) });

  return {
    nav: {
      home: h("nav.home"),
      about: h("nav.about"),
      assistant: h("nav.assistant"),
      services: h("nav.services"),
      tools: h("nav.tools"),
      areas: h("nav.areas"),
      posts: h("nav.posts"),
      contact: h("nav.contact"),
      menu: h("nav.menu"),
      close: h("nav.close"),
    },
    pages: {
      about: { title: h("pages.about.title"), blurb: (name: string) => h("pages.about.blurb", { name }) },
      services: { title: h("pages.services.title"), blurb: (name: string) => h("pages.services.blurb", { name }) },
      tools: { title: h("pages.tools.title"), blurb: (name: string) => h("pages.tools.blurb", { name }) },
      areas: { title: h("pages.areas.title"), blurb: (name: string) => h("pages.areas.blurb", { name }) },
      posts: { title: h("pages.posts.title"), blurb: (name: string) => h("pages.posts.blurb", { name }) },
      contact: { title: h("pages.contact.title"), blurb: (name: string) => h("pages.contact.blurb", { name }) },
    },
    seeAll: {
      services: h("seeAll.services"),
      tools: h("seeAll.tools"),
      areas: h("seeAll.areas"),
      posts: h("seeAll.posts"),
      about: h("seeAll.about"),
    },
    cta: {
      home_value: h("cta.home_value"),
      find_home: h("cta.find_home"),
      ai_chat: h("cta.ai_chat"),
      book: h("cta.book"),
      contact: h("cta.contact"),
      call: h("cta.call"),
      email: h("cta.email"),
      url: h("cta.url"),
    },
    hero: {
      headline: (name: string) => h("hero.defaultHeadline", { name }),
      subheadline: h("hero.defaultSubheadline"),
      serving: h("hero.serving"),
      years: (count: number) => h("hero.years", { count }),
      languages: h("hero.languages"),
      aiPowered: h("hero.aiPowered"),
    },
    assistant: {
      kicker: h("assistant.kicker"),
      title: h("assistant.title"),
      blurb: h("assistant.blurb"),
      greeting: (name: string) => h("assistant.greeting", { name }),
      placeholder: h("assistant.placeholder"),
      send: h("assistant.send"),
      thinking: h("assistant.thinking"),
      disclaimer: (name: string) => h("assistant.disclaimer", { name }),
      error: h("assistant.error"),
      retry: h("assistant.retry"),
      limit: h("assistant.limit"),
      leadCaptured: h("assistant.leadCaptured"),
      suggested: h("assistant.suggested"),
      unavailable: h("assistant.unavailable"),
      newChat: h("assistant.newChat"),
      you: h("assistant.you"),
      assistantName: (name: string) => h("assistant.assistantName", { name }),
      prompts: {
        find_homes: h("assistant.prompts.find_homes"),
        home_worth: h("assistant.prompts.home_worth"),
        afford: h("assistant.prompts.afford"),
        market: h("assistant.prompts.market"),
        sell: h("assistant.prompts.sell"),
        invest: h("assistant.prompts.invest"),
        schedule: h("assistant.prompts.schedule"),
      },
    },
    workforce: {
      kicker: h("workforce.kicker"),
      title: h("workforce.title"),
      blurb: (name: string) => h("workforce.blurb", { name }),
      tagline: h("workforce.tagline"),
      roles: {
        receptionist: { title: h("workforce.roles.receptionist.title"), desc: h("workforce.roles.receptionist.desc") },
        sales_assistant: { title: h("workforce.roles.sales_assistant.title"), desc: h("workforce.roles.sales_assistant.desc") },
        marketing_assistant: {
          title: h("workforce.roles.marketing_assistant.title"),
          desc: h("workforce.roles.marketing_assistant.desc"),
        },
        transaction_assistant: {
          title: h("workforce.roles.transaction_assistant.title"),
          desc: h("workforce.roles.transaction_assistant.desc"),
        },
        accountant: { title: h("workforce.roles.accountant.title"), desc: h("workforce.roles.accountant.desc") },
      },
      howTitle: h("workforce.howTitle"),
      howBlurb: h("workforce.howBlurb"),
      howNote: h("workforce.howNote"),
      steps: {
        missed_call: h("workforce.steps.missed_call"),
        receptionist: h("workforce.steps.receptionist"),
        lead: h("workforce.steps.lead"),
        qualify: h("workforce.steps.qualify"),
        followup: h("workforce.steps.followup"),
        appointment: h("workforce.steps.appointment"),
        crm: h("workforce.steps.crm"),
      },
    },
    services: {
      kicker: h("services.kicker"),
      title: h("services.title"),
      presets: {
        buy: { name: h("services.presets.buy.name"), desc: h("services.presets.buy.desc") },
        sell: { name: h("services.presets.sell.name"), desc: h("services.presets.sell.desc") },
        invest: { name: h("services.presets.invest.name"), desc: h("services.presets.invest.desc") },
        relocate: { name: h("services.presets.relocate.name"), desc: h("services.presets.relocate.desc") },
        new_construction: {
          name: h("services.presets.new_construction.name"),
          desc: h("services.presets.new_construction.desc"),
        },
        analysis: { name: h("services.presets.analysis.name"), desc: h("services.presets.analysis.desc") },
        custom: { name: h("services.presets.custom.name"), desc: "" },
      },
    },
    tools: {
      kicker: h("tools.kicker"),
      title: h("tools.title"),
      blurb: h("tools.blurb"),
      open: h("tools.open"),
      free: h("tools.free"),
      items: {
        home_value: { name: h("tools.items.home_value.name"), desc: h("tools.items.home_value.desc") },
        find_home: { name: h("tools.items.find_home.name"), desc: h("tools.items.find_home.desc") },
        mortgage: { name: h("tools.items.mortgage.name"), desc: h("tools.items.mortgage.desc") },
        affordability: { name: h("tools.items.affordability.name"), desc: h("tools.items.affordability.desc") },
        down_payment: { name: h("tools.items.down_payment.name"), desc: h("tools.items.down_payment.desc") },
        closing_cost: { name: h("tools.items.closing_cost.name"), desc: h("tools.items.closing_cost.desc") },
        rent_vs_buy: { name: h("tools.items.rent_vs_buy.name"), desc: h("tools.items.rent_vs_buy.desc") },
        refinance: { name: h("tools.items.refinance.name"), desc: h("tools.items.refinance.desc") },
        cash_flow: { name: h("tools.items.cash_flow.name"), desc: h("tools.items.cash_flow.desc") },
        cap_rate_roi: { name: h("tools.items.cap_rate_roi.name"), desc: h("tools.items.cap_rate_roi.desc") },
        roi: { name: h("tools.items.roi.name"), desc: h("tools.items.roi.desc") },
        investment_analyzer: {
          name: h("tools.items.investment_analyzer.name"),
          desc: h("tools.items.investment_analyzer.desc"),
        },
      } as Record<string, { name: string; desc: string }>,
    },
    homeValue: {
      kicker: h("homeValue.kicker"),
      title: h("homeValue.title"),
      body: h("homeValue.body"),
      cta: h("homeValue.cta"),
      address: h("homeValue.address"),
      addressPlaceholder: h("homeValue.addressPlaceholder"),
      estimate: h("homeValue.estimate"),
      estimating: h("homeValue.estimating"),
      estimateFailed: h("homeValue.estimateFailed"),
      estimateTitle: h("homeValue.estimateTitle"),
      rangeLabel: h("homeValue.rangeLabel"),
      unlockTitle: h("homeValue.unlockTitle"),
      unlockBody: (name: string) => h("homeValue.unlockBody", { name }),
      unlockCta: h("homeValue.unlockCta"),
      doneTitle: h("homeValue.doneTitle"),
      doneBody: (name: string) => h("homeValue.doneBody", { name }),
      disclaimer: h("homeValue.disclaimer"),
      back: h("homeValue.back"),
      steps: { address: h("homeValue.steps.address"), estimate: h("homeValue.steps.estimate"), report: h("homeValue.steps.report") },
    },
    areas: {
      kicker: h("areas.kicker"),
      title: (location: string) => h("areas.title", { location }),
      blurb: h("areas.blurb"),
      ask: h("areas.ask"),
    },
    area: {
      kicker: h("area.kicker"),
      title: (area: string) => h("area.title", { area }),
      intro: (name: string, area: string) => h("area.intro", { name, area }),
      metaDescription: (name: string, area: string) => h("area.metaDescription", { name, area }),
      posts: (area: string) => h("area.posts", { area }),
      noPosts: h("area.noPosts"),
      askAbout: (area: string) => h("area.askAbout", { area }),
      searchIn: (area: string) => h("area.searchIn", { area }),
      otherAreas: h("area.otherAreas"),
      back: h("area.back"),
      viewArea: h("area.viewArea"),
    },
    featured: {
      kicker: h("featured.kicker"),
      title: h("featured.title"),
      open: h("featured.open"),
      post: h("featured.post"),
      tool: h("featured.tool"),
      link: h("featured.link"),
    },
    feed: {
      title: h("feedTitle"),
      all: h("feedAll"),
      newest: h("feedOrderNewest"),
      oldest: h("feedOrderOldest"),
      readOn: h("feedReadOn"),
      alsoOn: h("feedAlsoOn"),
      filterLabel: h("feedFilterLabel"),
      orderLabel: h("feedOrderLabel"),
      empty: h("feedEmpty"),
    },
    trust: {
      kicker: h("trust.kicker"),
      title: h("trust.title"),
      years: h("trust.years"),
      yearsValue: (count: number) => h("trust.yearsValue", { count }),
      areas: h("trust.areas"),
      specialties: h("trust.specialties"),
      languages: h("trust.languages"),
      credentials: h("trust.credentials"),
      tech: h("trust.tech"),
      techBody: h("trust.techBody"),
      testimonials: h("trust.testimonials"),
      brokerage: h("trust.brokerage"),
    },
    finalCta: {
      title: h("finalCta.title"),
      body: (name: string) => h("finalCta.body", { name }),
    },
    contact: {
      title: h("formTitle"),
      blurb: h("formBlurb"),
      name: h("fieldName"),
      email: h("fieldEmail"),
      phone: h("fieldPhone"),
      message: h("fieldMessage"),
      intent: h("contact.intent"),
      intents: {
        buy: h("contact.intents.buy"),
        sell: h("contact.intents.sell"),
        invest: h("contact.intents.invest"),
        rent: h("contact.intents.rent"),
        relocate: h("contact.intents.relocate"),
        consult: h("contact.intents.consult"),
        other: h("contact.intents.other"),
      },
      consent: h("consentLabel"),
      submit: h("submit"),
      submitting: h("submitting"),
      thanksTitle: h("thanksTitle"),
      thanksBody: h("thanksBody"),
      errorGeneric: h("errorGeneric"),
      errorName: h("errorName"),
      errorContact: h("errorContact"),
      orCall: h("contact.orCall"),
      orEmail: h("contact.orEmail"),
      orBook: h("contact.orBook"),
    },
    footer: {
      license: h("licenseLabel"),
      poweredBy: h("poweredBy"),
      privacy: h("footer.privacy"),
      terms: h("footer.terms"),
      fairHousing: h("footer.fairHousing"),
      social: h("footer.social"),
    },
    sticky: {
      chat: h("sticky.chat"),
    },
    book: {
      kicker: h("book.kicker"),
      title: (name: string) => h("book.title", { name }),
      blurb: h("book.blurb"),
      pickDate: h("book.pickDate"),
      pickTime: h("book.pickTime"),
      closed: h("book.closed"),
      noSlots: h("book.noSlots"),
      loadingSlots: h("book.loadingSlots"),
      yourDetails: h("book.yourDetails"),
      meetingMode: h("book.meetingMode"),
      modes: { phone: h("book.modes.phone"), video: h("book.modes.video"), in_person: h("book.modes.in_person") },
      notes: h("book.notes"),
      confirm: h("book.confirm"),
      confirming: h("book.confirming"),
      doneTitle: h("book.doneTitle"),
      doneBody: (name: string) => h("book.doneBody", { name }),
      requestTitle: h("book.requestTitle"),
      requestBody: (name: string) => h("book.requestBody", { name }),
      externalTitle: h("book.externalTitle"),
      externalBody: h("book.externalBody"),
      externalCta: h("book.externalCta"),
      failed: h("book.failed"),
      slotTaken: h("book.slotTaken"),
      back: h("book.back"),
      duration: (count: number) => h("book.duration", { count }),
    },
    common: {
      comingSoonTitle: h("comingSoonTitle"),
      comingSoonBody: h("comingSoonBody"),
      notFoundTitle: h("notFoundTitle"),
      notFoundBody: h("notFoundBody"),
      backToHub: h("backToHub"),
      exampleTag: h("common.example"),
      previewBanner: h("common.previewBanner"),
      previewPublish: h("common.previewPublish"),
    },
  };
}

export type HubLabels = ReturnType<typeof hubLabels>;
