/**
 * The Settings page, card by card.
 *
 * Every card an agent can see on /dashboard/settings appears here exactly once,
 * in the order it appears in the product, paired with the guide that explains it
 * and a screenshot of the card itself. This is the list the /help/settings
 * reference page renders, and the source of the screenshot each settings guide
 * shows under "What it looks like".
 *
 * Two rules that keep this honest:
 *
 *  1. One card, one guide. If a card has no guide, it does not belong in the
 *     product — and if a guide covers two cards, agents cannot find either.
 *  2. The screenshots are generated, not hand-cropped. `capture-settings.mjs`
 *     signs into the sandboxed test account, walks the four tabs, and shoots
 *     each card element. Re-run it when the UI changes; do not touch the PNGs
 *     by hand, and never capture from a real agent's account.
 *
 * `Daily Briefings` is absent because it is no longer a Settings card — it
 * moved to Ask Max, where the briefing it schedules actually appears.
 *
 * `Recent calls` is deliberately absent: it renders live call rows with real
 * names and numbers, so it is excluded from capture and has no guide.
 */

/** The four tabs, in the order the Settings page shows them. */
export const SETTINGS_TABS = [
  "Voice & Style",
  "Messages",
  "Data & Tools",
  "Channels & Compliance",
] as const;

export type SettingsTab = (typeof SETTINGS_TABS)[number];

export type SettingsCard = {
  /** The heading exactly as it reads in the product. */
  card: string;
  tab: SettingsTab;
  /** Slug of the guide that explains this card. */
  guide: string;
  /** One line: what this card decides. */
  summary: string;
  /** Screenshot under /public, generated by capture-settings.mjs. */
  image: string;
};

export const SETTINGS_CARDS: ReadonlyArray<SettingsCard> = [
  // ── Voice & Style ──────────────────────────────────────────────────────────
  {
    card: "Language",
    tab: "Voice & Style",
    guide: "app-language",
    summary: "The language your dashboard is in. Separate from what the AI writes to contacts.",
    image: "/help/settings/language.png",
  },
  {
    card: "AI Assistant Style",
    tab: "Voice & Style",
    guide: "ai-voice-style",
    summary: "How the AI writes: personality, outbound language, and your own style notes.",
    image: "/help/settings/ai-assistant-style.png",
  },
  {
    card: "Phone Voice",
    tab: "Voice & Style",
    guide: "assistant-voice",
    summary: "How your phone assistant sounds to callers, and whether it greets them bilingually.",
    image: "/help/settings/phone-voice.png",
  },
  {
    card: "AI Voice Receptionist",
    tab: "Voice & Style",
    guide: "voice-ai-inbound",
    summary: "Who answers your inbound calls, what it knows about your business, and your office hours.",
    image: "/help/settings/ai-voice-receptionist.png",
  },
  {
    card: "Missed Call Text-Back",
    tab: "Voice & Style",
    guide: "missed-call-text-back",
    summary: "The SMS that goes out when you cannot pick up, and where your calls forward.",
    image: "/help/settings/missed-call-text-back.png",
  },

  // ── Messages ───────────────────────────────────────────────────────────────
  {
    card: "Review Policy",
    tab: "Messages",
    guide: "review-policy",
    summary: "Whether triggered messages send on their own or wait for you. The most consequential setting here.",
    image: "/help/settings/review-policy.png",
  },
  {
    card: "Message Templates",
    tab: "Messages",
    guide: "templates",
    summary: "The text of every message sent on your behalf, and which ones are allowed to autosend.",
    image: "/help/settings/message-templates.png",
  },
  {
    card: "Timing & Frequency",
    tab: "Messages",
    guide: "message-timing",
    summary: "Quiet hours, the daily cap per contact, and the pause after someone replies.",
    image: "/help/settings/timing-and-frequency.png",
  },
  {
    card: "Sphere drip cadence",
    tab: "Messages",
    guide: "sphere-drip-settings",
    summary: "A six-touch background nurture for your best past clients.",
    image: "/help/settings/sphere-drip-cadence.png",
  },

  // ── Data & Tools ───────────────────────────────────────────────────────────
  {
    card: "Home Value Smart Link",
    tab: "Data & Tools",
    guide: "home-value-smart-link",
    summary: "The link you share with homeowners: they enter an address, you get the lead.",
    image: "/help/settings/home-value-smart-link.png",
  },
  {
    card: "MLS Data Import",
    tab: "Data & Tools",
    guide: "lead-import",
    summary: "Bring contacts in from a CSV or another CRM, duplicate-aware.",
    image: "/help/settings/mls-data-import.png",
  },

  // ── Channels & Compliance ──────────────────────────────────────────────────
  {
    card: "Channels",
    tab: "Channels & Compliance",
    guide: "sending-identity",
    summary: "The phone number and email address your contacts actually see. Read-only.",
    image: "/help/settings/channels.png",
  },
  {
    card: "Connected social accounts",
    tab: "Channels & Compliance",
    guide: "connect-social-accounts",
    summary: "Where the pointer to connect Facebook, Instagram, LinkedIn and Threads lives.",
    image: "/help/settings/connected-social-accounts.png",
  },
  {
    card: "Social auto-posting",
    tab: "Channels & Compliance",
    guide: "social-autopilot",
    summary: "How often to post, where, about what — and who signs off before it publishes.",
    image: "/help/settings/social-auto-posting.png",
  },
  {
    card: "Weekly post schedule",
    tab: "Channels & Compliance",
    guide: "weekly-social-schedule",
    summary: "Pick the days yourself: per day a format, a time, channels, and a topic.",
    image: "/help/settings/weekly-post-schedule.png",
  },
  {
    card: "IDX lead routing",
    tab: "Channels & Compliance",
    guide: "idx-lead-routing",
    summary: "Whether inbound IDX leads are handed to you in rotation, and which ZIPs you serve.",
    image: "/help/settings/idx-lead-routing.png",
  },
  {
    card: "Transaction Coordinator notifications",
    tab: "Channels & Compliance",
    guide: "deal-notifications",
    summary: "The task digest, the growth digest, and the wire-fraud alert you should leave on.",
    image: "/help/settings/transaction-coordinator-notifications.png",
  },
  {
    card: "Commission defaults",
    tab: "Channels & Compliance",
    guide: "commission-defaults",
    summary: "Splits that pre-fill new deals and drive your revenue numbers.",
    image: "/help/settings/commission-defaults.png",
  },
  {
    card: "Compliance",
    tab: "Channels & Compliance",
    guide: "compliance-guardrails",
    summary: "The rules enforced for you, which cannot be switched off.",
    image: "/help/settings/compliance.png",
  },
];

/** The card a guide documents, if it documents one. */
export function cardForGuide(slug: string): SettingsCard | null {
  return SETTINGS_CARDS.find((c) => c.guide === slug) ?? null;
}

/** Cards grouped by tab, in product order, skipping tabs with nothing to show. */
export function cardsByTab(): Array<{ tab: SettingsTab; cards: SettingsCard[] }> {
  return SETTINGS_TABS.map((tab) => ({
    tab,
    cards: SETTINGS_CARDS.filter((c) => c.tab === tab),
  })).filter((g) => g.cards.length > 0);
}
