"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { diffRules } from "@/lib/compensation/diff";
import { bpsToPercent, formatBps, percentToBps } from "@/lib/compensation/format";
import type { CompensationRules, RevenueEventType } from "@/lib/compensation/types";
import { Button } from "@/components/ui/button";
import { cx } from "@/components/ui/primitives";

const EVENT_TYPES: { value: RevenueEventType; label: string }[] = [
  { value: "new_subscription", label: "New subscriptions" },
  { value: "renewal", label: "Renewals" },
  { value: "upgrade", label: "Upgrades" },
  { value: "add_on", label: "Add-ons" },
  { value: "expansion", label: "Expansion revenue" },
  { value: "one_time", label: "One-time charges" },
];

const clone = (rules: CompensationRules): CompensationRules =>
  JSON.parse(JSON.stringify(rules)) as CompensationRules;

export function CompensationEditor({
  planId,
  planName,
  currentRules,
  currentLabel,
  suggestedLabel,
  suggestedEffectiveFrom,
}: {
  planId: string;
  planName: string;
  currentRules: CompensationRules;
  currentLabel: string;
  suggestedLabel: string;
  suggestedEffectiveFrom: string;
}) {
  const router = useRouter();
  const [rules, setRules] = useState<CompensationRules>(() => clone(currentRules));
  const [label, setLabel] = useState(suggestedLabel);
  const [effectiveFrom, setEffectiveFrom] = useState(suggestedEffectiveFrom);
  const [reason, setReason] = useState("");
  const [status, setStatus] = useState<"draft" | "active">("draft");
  const [transitionPolicy, setTransitionPolicy] = useState<
    "grandfather" | "migrate_on_renewal" | "migrate_immediately"
  >("grandfather");
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState<{ tone: "ok" | "error"; text: string } | null>(null);

  const changes = useMemo(() => diffRules(currentRules, rules), [currentRules, rules]);

  const update = (mutate: (draft: CompensationRules) => void) =>
    setRules((prev) => {
      const draft = clone(prev);
      mutate(draft);
      return draft;
    });

  async function submit(event: React.FormEvent) {
    event.preventDefault();
    setSaving(true);
    setMessage(null);
    try {
      const response = await fetch("/api/admin/compensation", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          planId,
          label,
          effectiveFrom,
          rules,
          reason,
          status,
          transitionPolicy,
        }),
      });
      const result = (await response.json()) as { ok: boolean; message?: string };
      if (!response.ok || !result.ok) {
        setMessage({
          tone: "error",
          text: result.message ?? "We could not save this version. Please try again.",
        });
        return;
      }
      setMessage({ tone: "ok", text: result.message ?? "Version saved." });
      setReason("");
      router.refresh();
    } catch {
      setMessage({
        tone: "error",
        text: "We could not reach the server. Nothing was saved - please try again.",
      });
    } finally {
      setSaving(false);
    }
  }

  const yearCount = Math.max(1, Math.ceil(rules.direct.durationMonths / 12));

  return (
    <form onSubmit={submit} className="space-y-6">
      <Panel
        title="Direct commission"
        detail={`Rate per commission year, counted from each customer's start date. Currently ${formatBps(currentRules.direct.yearRatesBps[0] ?? 0)} in year one.`}
      >
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {Array.from({ length: yearCount }, (_, i) => (
            <NumberField
              key={i}
              label={`Year ${i + 1} rate`}
              suffix="%"
              value={bpsToPercent(rules.direct.yearRatesBps[i] ?? 0)}
              min={0}
              max={100}
              step={0.5}
              onChange={(value) =>
                update((draft) => {
                  const next = [...draft.direct.yearRatesBps];
                  while (next.length < yearCount) next.push(0);
                  next[i] = percentToBps(value);
                  draft.direct.yearRatesBps = next.slice(0, yearCount);
                })
              }
            />
          ))}
          <NumberField
            label="Duration"
            suffix="months"
            value={rules.direct.durationMonths}
            min={1}
            max={600}
            step={1}
            onChange={(value) => update((draft) => (draft.direct.durationMonths = value))}
          />
        </div>
      </Panel>

      <Panel
        title="Leadership Override"
        detail="Paid to qualified Leaders on qualifying customer revenue generated by Partners they personally developed."
      >
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          <NumberField
            label="Generations"
            value={rules.leadership.maxGenerations}
            min={0}
            max={10}
            step={1}
            onChange={(value) =>
              update((draft) => {
                draft.leadership.maxGenerations = value;
                const next = [...draft.leadership.generationRatesBps];
                while (next.length < value) next.push(0);
                draft.leadership.generationRatesBps = next.slice(0, Math.max(value, 1));
              })
            }
          />
          {Array.from({ length: Math.max(1, rules.leadership.maxGenerations) }, (_, i) => (
            <NumberField
              key={i}
              label={`Generation ${i + 1} rate`}
              suffix="%"
              value={bpsToPercent(rules.leadership.generationRatesBps[i] ?? 0)}
              min={0}
              max={100}
              step={0.5}
              onChange={(value) =>
                update((draft) => {
                  const next = [...draft.leadership.generationRatesBps];
                  while (next.length <= i) next.push(0);
                  next[i] = percentToBps(value);
                  draft.leadership.generationRatesBps = next;
                })
              }
            />
          ))}
          <NumberField
            label="Duration"
            suffix="months"
            value={rules.leadership.durationMonths}
            min={0}
            max={600}
            step={1}
            onChange={(value) => update((draft) => (draft.leadership.durationMonths = value))}
          />
        </div>
      </Panel>

      <Panel title="Leader qualification" detail="What a Partner must have before an override is paid.">
        <div className="grid gap-4 sm:grid-cols-2">
          <NumberField
            label="Minimum active personal customers"
            value={rules.leaderQualification.minPersonalActiveCustomers}
            min={0}
            max={1000}
            step={1}
            onChange={(value) =>
              update((draft) => (draft.leaderQualification.minPersonalActiveCustomers = value))
            }
          />
          <NumberField
            label="Minimum active Direct Partners"
            value={rules.leaderQualification.minActiveDirectPartners}
            min={0}
            max={100}
            step={1}
            onChange={(value) =>
              update((draft) => (draft.leaderQualification.minActiveDirectPartners = value))
            }
          />
          <Toggle
            label="Require Academy leadership training"
            checked={rules.leaderQualification.requireAcademyTraining}
            onChange={(checked) =>
              update((draft) => (draft.leaderQualification.requireAcademyTraining = checked))
            }
          />
          <Toggle
            label="Require good standing"
            checked={rules.leaderQualification.requireGoodStanding}
            onChange={(checked) =>
              update((draft) => (draft.leaderQualification.requireGoodStanding = checked))
            }
          />
        </div>
      </Panel>

      <Panel title="Qualifying revenue" detail="What the commission percentage is applied to.">
        <div className="flex flex-wrap gap-2">
          {EVENT_TYPES.map((type) => {
            const checked = rules.qualifyingRevenue.eligibleEventTypes.includes(type.value);
            return (
              <label
                key={type.value}
                className={cx(
                  "cursor-pointer rounded-xl border px-4 py-2.5 text-sm font-medium transition-colors",
                  checked
                    ? "border-navy-900 bg-navy-900 text-white"
                    : "border-hairline bg-white text-navy-700 hover:border-navy-300",
                )}
              >
                <input
                  type="checkbox"
                  className="sr-only"
                  checked={checked}
                  onChange={(e) =>
                    update((draft) => {
                      draft.qualifyingRevenue.eligibleEventTypes = e.target.checked
                        ? [...draft.qualifyingRevenue.eligibleEventTypes, type.value]
                        : draft.qualifyingRevenue.eligibleEventTypes.filter(
                            (t) => t !== type.value,
                          );
                    })
                  }
                />
                {type.label}
              </label>
            );
          })}
        </div>

        <div className="mt-5 grid gap-4 sm:grid-cols-2">
          <Toggle
            label="Exclude taxes"
            checked={rules.qualifyingRevenue.excludeTaxes}
            onChange={(v) => update((d) => (d.qualifyingRevenue.excludeTaxes = v))}
          />
          <Toggle
            label="Commission net of customer discount"
            checked={rules.qualifyingRevenue.commissionOnNetOfDiscount}
            onChange={(v) => update((d) => (d.qualifyingRevenue.commissionOnNetOfDiscount = v))}
          />
          <Toggle
            label="Exclude account credits"
            checked={rules.qualifyingRevenue.excludeCredits}
            onChange={(v) => update((d) => (d.qualifyingRevenue.excludeCredits = v))}
          />
          <Toggle
            label="Reverse on refund"
            checked={rules.qualifyingRevenue.reverseOnRefund}
            onChange={(v) => update((d) => (d.qualifyingRevenue.reverseOnRefund = v))}
          />
          <Toggle
            label="Reverse on chargeback"
            checked={rules.qualifyingRevenue.reverseOnChargeback}
            onChange={(v) => update((d) => (d.qualifyingRevenue.reverseOnChargeback = v))}
          />
          <NumberField
            label="Minimum qualifying revenue"
            suffix="$"
            value={rules.qualifyingRevenue.minimumQualifyingRevenueCents / 100}
            min={0}
            max={100000}
            step={1}
            onChange={(value) =>
              update(
                (d) =>
                  (d.qualifyingRevenue.minimumQualifyingRevenueCents = Math.round(value * 100)),
              )
            }
          />
        </div>
      </Panel>

      <Panel title="Customer discount" detail="The promotional offer a Partner's code can carry.">
        <div className="grid gap-4 sm:grid-cols-3">
          <NumberField
            label="Default discount"
            suffix="%"
            value={bpsToPercent(rules.customerDiscount.defaultDiscountBps)}
            min={0}
            max={100}
            step={0.5}
            onChange={(v) => update((d) => (d.customerDiscount.defaultDiscountBps = percentToBps(v)))}
          />
          <NumberField
            label="Maximum discount"
            suffix="%"
            value={bpsToPercent(rules.customerDiscount.maxDiscountBps)}
            min={0}
            max={100}
            step={0.5}
            onChange={(v) => update((d) => (d.customerDiscount.maxDiscountBps = percentToBps(v)))}
          />
          <NumberField
            label="Discount duration"
            suffix="months"
            value={rules.customerDiscount.discountDurationMonths}
            min={0}
            max={600}
            step={1}
            onChange={(v) => update((d) => (d.customerDiscount.discountDurationMonths = v))}
          />
        </div>
      </Panel>

      <Panel
        title="Version and transition"
        detail="A change never edits a live version. It creates a new one with its own effective date."
      >
        <div className="grid gap-4 sm:grid-cols-2">
          <TextField label="Version label" value={label} onChange={setLabel} placeholder="Plan V2" />
          <TextField
            label="Effective from"
            value={effectiveFrom}
            onChange={setEffectiveFrom}
            type="date"
          />
          <SelectField
            label="Status"
            value={status}
            onChange={(v) => setStatus(v as "draft" | "active")}
            options={[
              { value: "draft", label: "Draft - saved, no effect yet" },
              { value: "active", label: "Active - becomes the live plan" },
            ]}
          />
          <SelectField
            label="Existing customers"
            value={transitionPolicy}
            onChange={(v) =>
              setTransitionPolicy(v as "grandfather" | "migrate_on_renewal" | "migrate_immediately")
            }
            options={[
              { value: "grandfather", label: "Stay on their current version (recommended)" },
              { value: "migrate_on_renewal", label: "Move to this version at renewal" },
              { value: "migrate_immediately", label: "Move to this version immediately" },
            ]}
          />
        </div>

        <div className="mt-5">
          <label className="block">
            <span className="text-sm font-medium text-ink">
              Reason for this change <span className="text-rose-600">*</span>
            </span>
            <textarea
              value={reason}
              onChange={(e) => setReason(e.target.value)}
              rows={3}
              required
              placeholder="Why is this changing? This is recorded in the compensation change log and is what a Partner or a regulator will read."
              className="mt-1.5 w-full rounded-xl border border-hairline bg-white px-3.5 py-2.5 text-sm text-ink outline-none transition-colors focus:border-navy-400"
            />
          </label>
        </div>
      </Panel>

      {/* What will actually change */}
      <div className="rounded-2xl border border-hairline bg-white p-6 shadow-card">
        <h3 className="font-display text-base font-semibold tracking-tight text-ink">
          What changes against {currentLabel}
        </h3>
        {changes.length === 0 ? (
          <p className="mt-3 text-sm text-muted">
            Nothing yet. Adjust a setting above and the difference appears here before you save.
          </p>
        ) : (
          <ul className="mt-4 space-y-2.5">
            {changes.map((change) => (
              <li key={change.path} className="text-sm leading-relaxed text-[#33405a]">
                <span className="font-medium text-ink">{change.label}:</span>{" "}
                <span className="text-rose-700 line-through">{change.previous}</span>{" "}
                <span aria-hidden="true">&#8594;</span>{" "}
                <span className="font-semibold text-emerald-700">{change.next}</span>
              </li>
            ))}
          </ul>
        )}
        <p className="mt-5 rounded-xl border border-hairline bg-canvas-alt px-4 py-3 text-xs leading-relaxed text-muted">
          Saving creates a new plan version for <strong>{planName}</strong>. Commissions already
          calculated keep pointing at the version they were priced under and are never recalculated.
        </p>
      </div>

      {message ? (
        <div
          role="status"
          className={cx(
            "rounded-xl border px-4 py-3 text-sm",
            message.tone === "ok"
              ? "border-emerald-200 bg-emerald-50 text-emerald-800"
              : "border-rose-200 bg-rose-50 text-rose-800",
          )}
        >
          {message.text}
        </div>
      ) : null}

      <Button type="submit" size="lg" disabled={saving || changes.length === 0}>
        {saving
          ? "Saving..."
          : status === "active"
            ? "Create and activate version"
            : "Save as draft version"}
      </Button>
      {changes.length === 0 ? (
        <p className="text-xs text-muted">Change at least one setting to create a version.</p>
      ) : null}
    </form>
  );
}

/* -------------------------------------------------------------------------- */

function Panel({
  title,
  detail,
  children,
}: {
  title: string;
  detail: string;
  children: React.ReactNode;
}) {
  return (
    <section className="rounded-2xl border border-hairline bg-white p-6 shadow-card">
      <h3 className="font-display text-base font-semibold tracking-tight text-ink">{title}</h3>
      <p className="mt-1.5 text-sm leading-relaxed text-muted">{detail}</p>
      <div className="mt-5">{children}</div>
    </section>
  );
}

function NumberField({
  label,
  value,
  onChange,
  min,
  max,
  step,
  suffix,
}: {
  label: string;
  value: number;
  onChange: (value: number) => void;
  min: number;
  max: number;
  step: number;
  suffix?: string;
}) {
  return (
    <label className="block">
      <span className="text-xs font-semibold uppercase tracking-[0.1em] text-navy-500">
        {label}
      </span>
      <div className="mt-1.5 flex items-center gap-2">
        <input
          type="number"
          value={Number.isFinite(value) ? value : 0}
          min={min}
          max={max}
          step={step}
          onChange={(e) => onChange(Number(e.target.value))}
          className="w-full rounded-xl border border-hairline bg-white px-3.5 py-2.5 text-sm tabular-nums text-ink outline-none transition-colors focus:border-navy-400"
        />
        {suffix ? <span className="shrink-0 text-sm text-muted">{suffix}</span> : null}
      </div>
    </label>
  );
}

function TextField({
  label,
  value,
  onChange,
  type = "text",
  placeholder,
}: {
  label: string;
  value: string;
  onChange: (value: string) => void;
  type?: string;
  placeholder?: string;
}) {
  return (
    <label className="block">
      <span className="text-xs font-semibold uppercase tracking-[0.1em] text-navy-500">
        {label}
      </span>
      <input
        type={type}
        value={value}
        placeholder={placeholder}
        onChange={(e) => onChange(e.target.value)}
        className="mt-1.5 w-full rounded-xl border border-hairline bg-white px-3.5 py-2.5 text-sm text-ink outline-none transition-colors focus:border-navy-400"
      />
    </label>
  );
}

function SelectField({
  label,
  value,
  onChange,
  options,
}: {
  label: string;
  value: string;
  onChange: (value: string) => void;
  options: { value: string; label: string }[];
}) {
  return (
    <label className="block">
      <span className="text-xs font-semibold uppercase tracking-[0.1em] text-navy-500">
        {label}
      </span>
      <select
        value={value}
        onChange={(e) => onChange(e.target.value)}
        className="mt-1.5 w-full rounded-xl border border-hairline bg-white px-3.5 py-2.5 text-sm text-ink outline-none transition-colors focus:border-navy-400"
      >
        {options.map((option) => (
          <option key={option.value} value={option.value}>
            {option.label}
          </option>
        ))}
      </select>
    </label>
  );
}

/** The house toggle: green when on, grey when off, label beside it. */
function Toggle({
  label,
  checked,
  onChange,
}: {
  label: string;
  checked: boolean;
  onChange: (checked: boolean) => void;
}) {
  return (
    <label className="flex cursor-pointer items-center justify-between gap-4 rounded-xl border border-hairline bg-white px-4 py-3">
      <span className="text-sm text-[#33405a]">{label}</span>
      <span className="relative inline-flex shrink-0">
        <input
          type="checkbox"
          checked={checked}
          onChange={(e) => onChange(e.target.checked)}
          className="peer sr-only"
        />
        <span
          aria-hidden="true"
          className={cx(
            "block h-6 w-11 rounded-full transition-colors",
            checked ? "bg-emerald-500" : "bg-navy-200",
          )}
        />
        <span
          aria-hidden="true"
          className={cx(
            "absolute top-0.5 left-0.5 block h-5 w-5 rounded-full bg-white shadow transition-transform",
            checked && "translate-x-5",
          )}
        />
      </span>
    </label>
  );
}
