import { PageTitle } from "@/components/page-title";
import type { Metadata } from "next";
import { cookies } from "next/headers";
import { createClient } from "@/lib/supabase/server";
import { BooksNav } from "@/components/books-nav";
import { getServerT } from "@/lib/i18n/server";

export async function generateMetadata(): Promise<Metadata> {
  const t = await getServerT("books");
  return { title: t("accounts.metaTitle") };
}

// The enum values the DB stores; the labels live in `accounts.types.*`.
const TYPE_ORDER = ["asset", "liability", "equity", "revenue", "expense"] as const;
const TYPE_COLORS: Record<string, string> = {
  asset:     "bg-blue-50 text-blue-700",
  liability: "bg-rose-50 text-rose-700",
  equity:    "bg-purple-50 text-purple-700",
  revenue:   "bg-emerald-50 text-emerald-700",
  expense:   "bg-amber-50 text-amber-700",
};

export default async function AccountsPage() {
  const t = await getServerT("books");
  const cookieStore = await cookies();
  const orgId = cookieStore.get("helmsmart-org-id")?.value ?? "";
  const supabase = await createClient();

  const { data: accounts } = await supabase
    .from("chart_of_accounts")
    .select("id, code, name, type, normal_balance, tax_line_code, is_active, description")
    .eq("organization_id", orgId)
    .order("code");

  // Group by type
  const grouped = new Map<string, typeof accounts>();
  for (const acct of accounts ?? []) {
    const arr = grouped.get(acct.type) ?? [];
    arr.push(acct);
    grouped.set(acct.type, arr);
  }

  const total = accounts?.length ?? 0;
  const active = accounts?.filter((a) => a.is_active).length ?? 0;

  return (
    <div className="p-8 max-w-6xl mx-auto">
      <div className="flex items-center justify-between mb-6">
        <div>
          <PageTitle base="Books" />
          <p className="text-sm text-slate-500 mt-0.5">{t("accounts.subtitle")}</p>
        </div>
        <p className="text-xs text-slate-400">{t("accounts.activeCount", { active, total })}</p>
      </div>

      <BooksNav />

      <div className="mb-4">
        <h2 className="text-sm font-semibold text-slate-700">{t("accounts.title")}</h2>
        <p className="text-xs text-slate-400 mt-0.5">
          {t("accounts.autoGenerated")}{" "}
          <span className="text-amber-600 font-medium">{t("accounts.taxReviewWarning")}</span>
        </p>
      </div>

      <div className="space-y-6">
        {TYPE_ORDER.map((type) => {
          const typeAccounts = grouped.get(type);
          if (!typeAccounts?.length) return null;

          return (
            <div key={type} className="bg-white rounded-xl border border-slate-200 overflow-hidden">
              {/* Section header */}
              <div className="flex items-center gap-3 px-5 py-3 bg-slate-50 border-b border-slate-100">
                <span className={`inline-block px-2.5 py-0.5 rounded-full text-xs font-semibold ${TYPE_COLORS[type]}`}>
                  {t(`accounts.types.${type}`)}
                </span>
                <span className="text-xs text-slate-400">
                  {t("accounts.countInType", { count: typeAccounts.length })}
                </span>
              </div>

              {/* Column headers */}
              <div className="grid grid-cols-[80px_1fr_100px_80px] gap-4 px-5 py-2 border-b border-slate-50 text-xs font-medium text-slate-400 uppercase tracking-wide">
                <span>{t("accounts.columns.code")}</span>
                <span>{t("accounts.columns.name")}</span>
                <span>{t("accounts.columns.normalBalance")}</span>
                <span className="text-right">{t("accounts.columns.taxCode")}</span>
              </div>

              {/* Rows */}
              <div className="divide-y divide-slate-50">
                {typeAccounts.map((acct) => (
                  <div
                    key={acct.id}
                    className={`grid grid-cols-[80px_1fr_100px_80px] gap-4 px-5 py-2.5 items-center ${
                      acct.is_active ? "" : "opacity-40"
                    }`}
                  >
                    <span className="text-xs font-mono text-slate-500">{acct.code}</span>
                    <span className="text-sm text-slate-800">{acct.name}</span>
                    <span className="text-xs text-slate-500">
                      {t(`accounts.normalBalance.${acct.normal_balance}`, {
                        defaultValue: acct.normal_balance,
                      })}
                    </span>
                    <span className="text-xs text-right">
                      {acct.tax_line_code ? (
                        <code className="bg-slate-100 text-slate-700 px-1.5 py-0.5 rounded font-mono text-[10px]">
                          {acct.tax_line_code}
                        </code>
                      ) : (
                        <span className="text-slate-300">—</span>
                      )}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          );
        })}
      </div>

      {!total && (
        <div className="bg-white rounded-xl border border-slate-200 py-16 text-center text-sm text-slate-400">
          {t("accounts.empty")}
        </div>
      )}
    </div>
  );
}
