import type { Metadata } from "next";
import Link from "next/link";
import { PRODUCTS } from "@/content/products";
import { loadPublicRules } from "@/lib/compensation/repository";
import { formatBps, formatMonthsAsYears } from "@/lib/compensation/format";
import { CTA, DISCLAIMERS, SITE } from "@/lib/site";
import { ButtonLink } from "@/components/ui/button";
import { Disclaimer } from "@/components/ui/disclaimer";
import { Container, Eyebrow, Section, SectionHeading } from "@/components/ui/primitives";
import { ClosingCta, FeatureGrid, ProductCard, StepList } from "@/components/site/blocks";
import { DirectTotalHeadline, RateStrip } from "@/components/site/rate-strip";
import { EcosystemDiagram, FlowDiagram } from "@/components/site/visuals";
import { LevelLadder } from "@/components/site/levels";

/** Public content: statically rendered, refreshed periodically so a
 *  compensation change reaches visitors without a deploy. */
export const revalidate = 600;

export const metadata: Metadata = {
  // Absolute: the layout template would otherwise append the brand twice.
  title: { absolute: "AI Business Works Partner Program | Build Your AI Business" },
  description:
    "Become an AI Business Works Partner. Help businesses adopt AI with CloseBoss AI, MarketingBoss AI and HelmSmart AI, and earn recurring commissions on qualifying customer subscriptions.",
  alternates: { canonical: "/" },
};

const STEPS = [
  { title: "Join", body: "Register as an AI Business Works Partner. No inventory, no purchase requirement." },
  { title: "Learn", body: "Work through the Academy: what each product does, and which business problems it solves." },
  { title: "Connect", body: "Introduce businesses you already know to the right AI solution for their situation." },
  { title: "Earn", body: "Earn qualifying commissions when a referred customer subscribes and keeps paying." },
  { title: "Grow", body: "After meeting the requirements, develop Direct Partners and qualify for the Leadership Override." },
];

const OPPORTUNITY = [
  { title: "What to automate", body: "Most owners know AI matters. Very few know which part of their week is the right place to start." },
  { title: "AI for sales", body: "Responding first, following up consistently, and qualifying before a person spends an hour on a call." },
  { title: "AI for marketing", body: "Producing and distributing enough content to matter, without hiring a marketing department." },
  { title: "AI for operations", body: "The repeatable work that quietly consumes a business: intake, scheduling, updates, handoffs." },
  { title: "AI workflows", body: "Connecting the steps so work moves without someone chasing it." },
  { title: "AI-powered teams", body: "Giving an AI Workforce defined responsibilities, and keeping people where judgement is required." },
];

export default async function HomePage() {
  const { rules } = await loadPublicRules();
  const overrideBps = rules.leadership.generationRatesBps[0] ?? 0;
  const yearOneBps = rules.direct.yearRatesBps[0] ?? 0;

  return (
    <>
      {/* ------------------------------------------------------------------ */}
      {/* Hero                                                                */}
      {/* ------------------------------------------------------------------ */}
      <Section tone="dark" grid size="roomy" className="overflow-hidden pt-16 sm:pt-20">
        <Container>
          <div className="mx-auto max-w-3xl text-center">
            <Eyebrow tone="dark">AI Business Works Partner Program</Eyebrow>
            <h1 className="mt-5 font-display text-4xl leading-[1.05] font-semibold tracking-tight text-white sm:text-5xl lg:text-6xl">
              Build your AI business
            </h1>
            <p className="mt-6 text-lg leading-relaxed text-navy-200">
              Become an AI Business Works Partner and help businesses discover powerful AI
              solutions while earning recurring commissions from qualifying customer
              subscriptions.
            </p>
          </div>

          <div className="mx-auto mt-12 max-w-4xl">
            <RateStrip rules={rules} tone="dark" />
          </div>

          {overrideBps > 0 ? (
            <p className="mx-auto mt-8 max-w-2xl text-center text-sm leading-relaxed text-navy-300">
              Qualified Leaders can earn a {formatBps(overrideBps)} Leadership Override on
              qualifying customer revenue generated by their directly developed Partners, for up to{" "}
              {formatMonthsAsYears(rules.leadership.durationMonths)} per qualifying customer.
            </p>
          ) : null}

          <div className="mt-10 flex flex-col items-center justify-center gap-3 sm:flex-row">
            <ButtonLink href={CTA.primary.href} variant="onDark" size="lg">
              {CTA.primary.label}
            </ButtonLink>
            <ButtonLink
              href={CTA.secondary.href}
              variant="ghost"
              size="lg"
              className="text-white hover:bg-white/10 hover:text-white"
            >
              {CTA.secondary.label}
            </ButtonLink>
          </div>

          <div className="mx-auto mt-12 max-w-3xl">
            <Disclaimer tone="dark">{DISCLAIMERS.hero}</Disclaimer>
          </div>
        </Container>
      </Section>

      {/* ------------------------------------------------------------------ */}
      {/* The opportunity                                                     */}
      {/* ------------------------------------------------------------------ */}
      <Section tone="light">
        <Container>
          <SectionHeading
            eyebrow="Why now"
            title="The AI business opportunity is here"
            lead={
              <>
                Businesses are not short of AI headlines. They are short of someone who can tell
                them which part of their operation to change first, and what to use.
              </>
            }
          />
          <div className="mt-12">
            <FeatureGrid items={OPPORTUNITY} />
          </div>
          <p className="mt-10 max-w-3xl text-base leading-relaxed text-muted">
            AI Business Works builds practical AI solutions for those problems. Partners connect
            those solutions with the businesses that need them - starting, usually, with businesses
            they already know.
          </p>
        </Container>
      </Section>

      {/* ------------------------------------------------------------------ */}
      {/* Products                                                            */}
      {/* ------------------------------------------------------------------ */}
      <Section tone="alt">
        <Container width="wide">
          <SectionHeading
            eyebrow="The solutions"
            title={
              <>
                One Partner.
                <br />
                Multiple AI solutions.
              </>
            }
            lead="Three products, three different buyers. A Partner recommends the one that fits the business in front of them - and the ecosystem is built to add more."
          />
          <div className="mt-12 grid gap-5 lg:grid-cols-3">
            {PRODUCTS.map((product) => (
              <ProductCard key={product.key} product={product} />
            ))}
          </div>
          <div className="mt-8">
            <ButtonLink href={CTA.solutions.href} variant="secondary">
              {CTA.solutions.label}
            </ButtonLink>
          </div>
        </Container>
      </Section>

      {/* ------------------------------------------------------------------ */}
      {/* How it works                                                        */}
      {/* ------------------------------------------------------------------ */}
      <Section tone="light">
        <Container width="wide">
          <SectionHeading
            eyebrow="How it works"
            title="Five steps, in order"
            lead="Nothing here happens before the step before it. Commissions follow customers, and customers follow real work."
          />
          <div className="mt-12">
            <StepList steps={STEPS} />
          </div>
          <div className="mt-8">
            <ButtonLink href={CTA.secondary.href} variant="secondary">
              {CTA.secondary.label}
            </ButtonLink>
          </div>
        </Container>
      </Section>

      {/* ------------------------------------------------------------------ */}
      {/* Direct commissions                                                  */}
      {/* ------------------------------------------------------------------ */}
      <Section tone="navy" grid>
        <Container>
          <SectionHeading
            tone="dark"
            eyebrow="Direct commissions"
            title="Earn from the customers you refer"
            lead="For qualifying customers, Partners may receive a share of subscription revenue that steps down over the commission period."
          />

          <div className="mt-12 max-w-4xl">
            <RateStrip rules={rules} tone="dark" includeLeadership={false} />
          </div>

          <div className="mt-10">
            <DirectTotalHeadline rules={rules} tone="dark" />
            <p className="mt-4 max-w-2xl text-base leading-relaxed text-navy-200">
              Commission is calculated on qualifying revenue - what the customer is actually
              billed, net of any discount, excluding taxes and credits. Refunds and chargebacks
              reverse the commission attached to them.
            </p>
          </div>

          <div className="mt-10 max-w-3xl">
            <Disclaimer tone="dark">{DISCLAIMERS.structure}</Disclaimer>
          </div>

          <div className="mt-8">
            <ButtonLink href={CTA.compensation.href} variant="onDark">
              {CTA.compensation.label}
            </ButtonLink>
          </div>
        </Container>
      </Section>

      {/* ------------------------------------------------------------------ */}
      {/* Customer discount                                                   */}
      {/* ------------------------------------------------------------------ */}
      <Section tone="light">
        <Container>
          <SectionHeading
            eyebrow="Customer offer"
            title="Your customers get a special offer"
            lead={
              <>
                Every Partner receives a personal referral link, a personal discount code, a QR
                code and a Partner landing page. The customer can receive an applicable
                promotional discount, the Partner receives qualifying commission, and AI Business
                Works gains a customer.
              </>
            }
          />

          <div className="mt-12">
            <FlowDiagram
              steps={[
                { label: "Partner", detail: "You" },
                { label: "Personal link / code", detail: "Attribution recorded" },
                { label: "Customer", detail: "A business you introduced" },
                { label: "Discount", detail: "Applied at checkout", emphasis: true },
                { label: "AI solution", detail: "The product they adopt" },
                { label: "Partner commission", detail: "On qualifying revenue", emphasis: true },
              ]}
            />
          </div>

          <p className="mt-10 text-sm leading-relaxed text-muted">
            Customer discount amounts, durations and product-specific offers are configured by AI
            Business Works and can change. The current offer attached to your code always appears
            in your Partner dashboard.
          </p>
        </Container>
      </Section>

      {/* ------------------------------------------------------------------ */}
      {/* Leadership                                                          */}
      {/* ------------------------------------------------------------------ */}
      <Section tone="alt">
        <Container>
          <div className="grid gap-12 lg:grid-cols-2 lg:items-center">
            <div>
              <SectionHeading
                eyebrow="Leadership"
                title="Build more than a customer base"
                lead="Partners who demonstrate real customer success can become AI Business Works Leaders."
              />
              <ul className="mt-8 space-y-3">
                {[
                  `${rules.leaderQualification.minPersonalActiveCustomers} personally referred active paying customers`,
                  `${rules.leaderQualification.minActiveDirectPartners} active Direct Partner${rules.leaderQualification.minActiveDirectPartners === 1 ? "" : "s"}`,
                  rules.leaderQualification.requireAcademyTraining
                    ? "Applicable Academy and leadership training"
                    : "Academy training recommended",
                  "Good standing and compliance with the Partner Program Terms",
                ].map((item) => (
                  <li key={item} className="flex gap-3 text-[15px] leading-relaxed text-[#33405a]">
                    <span
                      aria-hidden="true"
                      className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-gold-accent"
                    />
                    {item}
                  </li>
                ))}
              </ul>
              <div className="mt-8">
                <ButtonLink href="/leadership" variant="secondary">
                  See the Leadership Program
                </ButtonLink>
              </div>
            </div>

            <div className="rounded-2xl border border-hairline bg-white p-7 shadow-card sm:p-8">
              <Eyebrow>Leadership Override</Eyebrow>
              <div className="mt-4 font-display text-6xl font-semibold tracking-tight text-gold-accent">
                {formatBps(overrideBps)}
              </div>
              <p className="mt-5 text-[15px] leading-relaxed text-muted">
                Of qualifying customer subscription revenue generated by a Partner you personally
                developed, for up to {formatMonthsAsYears(rules.leadership.durationMonths)} per
                qualifying customer.
              </p>
              <p className="mt-4 text-[15px] leading-relaxed text-muted">
                The override is paid on customer revenue. It is not paid for recruiting people.
              </p>
              <div className="mt-6 rounded-xl border border-hairline bg-canvas-alt px-4 py-3">
                <p className="text-xs font-semibold uppercase tracking-[0.12em] text-navy-600">
                  One level. Simple. Transparent.
                </p>
                <p className="mt-1.5 text-xs leading-relaxed text-muted">
                  The default plan pays{" "}
                  {rules.leadership.maxGenerations === 1
                    ? "a single generation"
                    : `${rules.leadership.maxGenerations} generations`}
                  . <Link href="/leadership#generations" className="underline underline-offset-4">
                    See exactly what that means
                  </Link>
                  .
                </p>
              </div>
            </div>
          </div>
        </Container>
      </Section>

      {/* ------------------------------------------------------------------ */}
      {/* Levels                                                              */}
      {/* ------------------------------------------------------------------ */}
      <Section tone="light">
        <Container width="wide">
          <SectionHeading
            eyebrow="Recognition"
            title="Partner levels"
            lead="Levels recognise the size of a Partner's active customer base. They are professional recognition, not a prize ladder."
          />
          <div className="mt-12">
            <LevelLadder />
          </div>
        </Container>
      </Section>

      {/* ------------------------------------------------------------------ */}
      {/* Ecosystem                                                           */}
      {/* ------------------------------------------------------------------ */}
      <Section tone="dark" grid>
        <Container width="wide">
          <SectionHeading
            tone="dark"
            eyebrow="The ecosystem"
            title="AI Business Works is bigger than any one product"
            lead={`${SITE.name} is a master AI business ecosystem. The Partner Program is its human distribution network.`}
          />
          <div className="mt-12">
            <EcosystemDiagram />
          </div>
        </Container>
      </Section>

      <ClosingCta rates={<RateStrip rules={rules} tone="dark" />} />

      {/* Structured data for the program itself. */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "WebPage",
            name: "AI Business Works Partner Program",
            description: metadata.description,
            url: SITE.url,
            about: {
              "@type": "Service",
              name: "AI Business Works Partner Program",
              serviceType: "AI solutions partner program",
              provider: { "@type": "Organization", name: SITE.name, url: SITE.url },
              description: `Partners help businesses adopt AI and may earn ${formatBps(yearOneBps)} of qualifying customer subscription revenue in commission year one under the current compensation plan, subject to the Partner Program Terms.`,
            },
          }),
        }}
      />
    </>
  );
}
