-- Social carousels (reach Phase 3a, PR 2). A carousel is an ordered slide deck
-- generated by lib/social/generateCarousel. Stored separately from the
-- single-image social_post_recommendations because the shape differs (N slides
-- + a caption) and the publish path (multi-image) is different.
--
-- Slides are rendered on the fly by /api/social/carousel/[id]/[slide]; the
-- optional slide_image_urls array caches the rendered PNGs once we persist them.

create table if not exists public.social_carousels (
  id uuid primary key default gen_random_uuid(),
  -- Brand-owned rows set agent_id (mirrors social_content_library's brand rows);
  -- null is allowed for shared/library carousels. bigint to match public.agents.id.
  agent_id bigint,
  voice text not null default 'brand' check (voice in ('founder', 'brand')),
  title text not null,
  caption text not null,
  -- Ordered slides: [{ "heading": "...", "body": "..." }, ...]. slides[0] = cover,
  -- last = close, middle = points.
  slides jsonb not null,
  hashtags text[] not null default '{}',
  -- Cached rendered slide PNGs (social-images bucket URLs), same index order as
  -- `slides`. Empty until persisted; the render route is the source of truth.
  slide_image_urls jsonb not null default '[]'::jsonb,
  status text not null default 'draft'
    check (status in ('draft', 'approved', 'scheduled', 'posted', 'dismissed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists social_carousels_agent_created_idx
  on public.social_carousels (agent_id, created_at desc);

-- RLS: this table is written/read by the service-role client only (same posture
-- as social_post_recommendations). Enable RLS with no policies so the anon/auth
-- session client can't touch it; service-role bypasses RLS.
alter table public.social_carousels enable row level security;

comment on table public.social_carousels is
  'Multi-slide social carousels (reach Phase 3a). Rendered by /api/social/carousel/[id]/[slide].';
