/**
 * Bundled legal drafts.
 *
 * These are the fallback copies. The live text lives in `abw_legal_documents`
 * and is edited and published from the admin dashboard, so counsel can revise
 * any of it without a code change or a rebuild. A page renders the database
 * version when one is published and falls back to the draft below otherwise.
 *
 * NOTHING HERE IS LEGAL ADVICE. Every document is a structural draft that must
 * be reviewed and rewritten by qualified counsel before public launch.
 */

export interface LegalDocument {
  key: string;
  title: string;
  summary: string;
  bodyMarkdown: string;
}

export const LEGAL_REVIEW_NOTICE =
  "Draft pending legal review. This document is a working draft and has not yet been reviewed by qualified counsel. It does not yet govern participation in the AI Business Works Partner Program.";

const partnerTerms = `
## 1. The agreement

These Partner Program Terms govern participation in the AI Business Works Partner Program. By registering as a Partner you agree to these Terms, the Privacy Policy, and the Partner Marketing Guidelines.

## 2. What a Partner is

A Partner is an independent contractor. A Partner is not an employee, agent, franchisee or joint venturer of AI Business Works, has no authority to bind AI Business Works, and may not represent themselves as doing so.

Partners are responsible for their own taxes, business expenses, and compliance with the laws of their jurisdiction.

## 3. Eligibility

To register, an applicant must be of legal age in their jurisdiction, provide accurate registration information, and be permitted to enter this agreement. AI Business Works may approve, decline, suspend or terminate any Partner account at its discretion, subject to the commission provisions in Section 7.

## 4. What a Partner does

A Partner introduces businesses to AI Business Works products, explains what those products do, and supports the customer relationship. A Partner does not resell the products, set pricing, or contract with customers on behalf of AI Business Works.

## 5. Customer attribution

A customer is attributed to a Partner when the customer subscribes through that Partner's referral link, referral code or discount code, in accordance with the attribution rules then in effect. Attribution is recorded at the time of subscription and is auditable.

An existing AI Business Works customer is not re-attributed to a Partner. Where two Partners have a competing claim, AI Business Works determines attribution from the platform's recorded attribution data.

## 6. Compensation

Compensation is governed by the compensation plan version in effect for the relevant customer, as published in the Commission Policy and shown in the Partner dashboard.

Commissions are calculated on qualifying revenue, which excludes taxes, credits, refunded amounts and charged-back amounts, and is calculated net of any customer discount applied.

Compensation plans are versioned with effective dates. Unless a published transition rule states otherwise, a customer remains on the plan version in effect on the date they subscribed, and historical commissions are not recalculated under a later version.

## 7. Payment

Commissions post as pending when the underlying revenue is recorded, become approved after the applicable review period, and are paid on the payout schedule and above the payout threshold stated in the Commission Policy.

AI Business Works may withhold or reverse a commission where the underlying revenue is refunded, charged back, or found to arise from a transaction that breaches these Terms.

## 8. Leadership

A Partner who meets the Leader qualification requirements published in the active compensation plan may earn a Leadership Override on qualifying customer revenue generated by Partners they personally developed, for the period and number of generations that plan specifies.

Leader status is reviewed on an ongoing basis. A Partner who no longer meets the requirements no longer earns the override for periods in which they were not qualified.

## 9. Conduct

A Partner must not: make income claims or earnings guarantees; describe illustrations as typical or expected results; misrepresent what a product does; use the AI Business Works or product names or marks except as the Marketing Guidelines permit; send unsolicited communications in breach of applicable law; create accounts or subscriptions for the purpose of generating commission; or pressure any person to register as a Partner.

## 10. Intellectual property

AI Business Works retains all rights in its brands, products, materials and platform. A Partner receives a limited, revocable, non-exclusive licence to use the supplied materials for the purpose of promoting AI Business Works products in line with the Marketing Guidelines.

## 11. Confidentiality and data

A Partner may receive customer and program information. That information may be used only to support the customer relationship, must be protected, and must not be sold, shared or retained after termination.

## 12. Term and termination

Either party may terminate at any time on written notice. On termination, commissions already earned on qualifying revenue recognised before termination remain payable under the applicable plan, except where termination follows a breach of Section 9.

## 13. Changes

AI Business Works may amend these Terms. Material changes will be notified to Partners, and the compensation effects of any change are governed by the plan versioning and transition rules in Section 6.

## 14. Disclaimers and limitation of liability

The program is provided as is. To the maximum extent permitted by law, AI Business Works is not liable for indirect or consequential loss, and its aggregate liability is limited to commissions paid to the Partner in the twelve months preceding the claim.

## 15. Governing law and disputes

Governing law, venue and dispute resolution to be completed by counsel.
`;

const privacyPolicy = `
## What this covers

This policy explains what AI Business Works collects through the Partner Program platform, why, and what choices you have.

## What we collect

**Partner registration.** Name, email, phone, country, state or province, business name, industry, website, primary market, how you heard about the program, and the products you are interested in.

**Partner account.** Your referral and discount codes, the customers attributed to you, your commission ledger, your Academy progress, and your payout settings.

**Public profile.** Only what you choose to publish, and only when you set your profile to public.

**Usage.** Referral link clicks associated with your codes, including a truncated or hashed IP address, user agent and referring page. We use this to attribute customers correctly and to detect abuse.

## What we do not collect here

The Partner platform does not store your bank account, card numbers or full tax identification numbers. Payout details are held by the payment provider; the platform stores only a reference to your account with that provider.

## Why we process it

To operate the Partner Program: creating your account, attributing customers, calculating and paying commissions, meeting tax and record-keeping obligations, preventing fraud, and communicating with you about the program.

## Who we share it with

Service providers who operate parts of the platform on our behalf (hosting, database, email, payments), under contract and only for those purposes. Authorities where the law requires it. We do not sell personal information.

## Customer data

Where you can see information about customers attributed to you, that information belongs to AI Business Works and its customers. You may use it only to support the customer relationship.

## Retention

Partner and commission records are retained for as long as required for tax, accounting and dispute purposes, and then deleted or anonymised.

## Your rights

Depending on where you live, you may have rights to access, correct, export or delete your personal information, and to object to certain processing. Contact us to exercise them.

## Security

Access to Partner and commission data is restricted at the database level: a Partner can read only their own customers, their own commissions and the Partners they personally sponsor.

## Contact

Contact details, data controller identity, international transfer mechanism and supervisory authority to be completed by counsel.
`;

const marketingGuidelines = `
## Why these guidelines exist

What a Partner says in public is what AI Business Works is understood to have said. These guidelines keep the program honest, and they protect you.

## The rule that matters most

**Never make an income claim.** Do not state, imply, or illustrate what someone can, will, or typically does earn. That includes screenshots of your own commissions, "I made X last month", income goals, and any figure attached to a recruiting message.

The compensation structure may be described factually. Results may not be promised.

## Describing the compensation plan

You may state the current rates, durations and qualification requirements exactly as published on this site.

You may show the commission simulator and describe it as an illustration.

You may not: call any figure typical or expected; present an illustration as a forecast; describe the override as passive or residual income; or say that Partners "earn while they sleep".

## Prohibited language

Do not use: get rich, financial freedom, quit your job, replace your income, life-changing income, guaranteed, risk-free, unlimited earnings, ground floor, or any variant of these.

Do not use imagery of luxury cars, cash, private jets or similar wealth signalling in connection with the program.

## Describing the products

Describe what the products do. Do not invent capabilities, quote performance numbers that AI Business Works has not published, or claim outcomes for a business you have not worked with.

Do not present AI Business Works products as legal, financial, tax or medical advice tools.

## Using names and marks

Use the full product names on first mention: CloseBoss AI, MarketingBoss AI, HelmSmart AI. Use the supplied logos without alteration.

Refer to another company's brand only where it is necessary to identify their product or service, and never in a way that suggests endorsement, affiliation or sponsorship.

## Your independence

Identify yourself as an independent AI Business Works Partner. Do not use a title that implies employment, and do not create a website, social profile, ad account or email address that could be mistaken for an official AI Business Works property.

## Advertising and outreach

Follow the law that applies to you for email, SMS, calling and advertising, including consent, identification and opt-out requirements. Do not buy ads on AI Business Works brand terms without written permission. Do not send unsolicited bulk messages.

## Testimonials

Only publish a customer's words with their written permission. Do not edit a testimonial in a way that changes its meaning, and do not present a single customer's outcome as representative.

## Enforcement

Marketing that breaches these guidelines must be corrected on request. Repeated or serious breaches may lead to suspension or termination under the Partner Program Terms.
`;

const commissionPolicy = `
## Purpose

This policy states how commissions are calculated, approved, paid and reversed. It sits alongside the Partner Program Terms and the active compensation plan version.

## Qualifying revenue

Commission is calculated on qualifying revenue: subscription revenue actually billed to the customer, net of any customer discount applied, excluding taxes, account credits, refunded amounts and charged-back amounts.

The revenue event types that qualify are set by the active compensation plan and are shown on the Compensation page.

## The commission period

The commission clock starts on the customer's start date, not on the Partner's join date. Commission year one runs for twelve months from the customer's start date, year two for the twelve months after that, and so on, up to the maximum direct commission period in the active plan.

## Which plan version applies

Each commission records the exact compensation plan and plan version used, and the inputs it was calculated from. Under the default transition policy a customer stays on the plan version in effect on the date they subscribed.

## Commission statuses

**Pending.** Calculated from recorded revenue and awaiting review.

**Approved.** Reviewed and cleared for payout.

**Paid.** Included in a completed payout.

**Reversed.** Cancelled by an adjustment, with a stated reason.

**Refunded.** Reversed because the underlying revenue was refunded.

**Chargeback.** Reversed because the underlying payment was charged back.

## Reversals

A reversal is a new ledger entry that points at the original. Historical commission records are never edited or deleted. The dashboard shows both the original and the reversal.

## Approval and payout

Commissions are reviewed before approval. Approved commissions are paid on the published payout schedule once the Partner's balance clears the payout threshold and any required tax documentation is complete.

Payout threshold, schedule, methods and tax documentation requirements are configured by AI Business Works and shown in the Partner dashboard.

## Disputes

A Partner may ask for a written explanation of any commission. The platform stores the plan version, rate, qualifying revenue and full calculation trace for every entry.

Dispute window and escalation process to be completed by counsel.
`;

const refundPolicy = `
## Customer refunds

Refund eligibility for AI Business Works products is governed by the terms of the product the customer subscribed to. This policy covers what a refund or chargeback means for Partner compensation.

## Effect on commission

Where a customer payment is refunded in whole or in part, the commission attributable to the refunded amount is reversed under the active compensation plan.

Where a payment is charged back, the commission attributable to the charged-back amount is reversed and the transaction is flagged for review.

## How reversals appear

A reversal is posted as its own entry in the commission ledger, linked to the original commission, with the reason recorded. The original entry is preserved.

If the reversal exceeds the Partner's pending balance, the negative balance is carried forward and offset against future commissions.

## Repeated chargebacks

A pattern of chargebacks on customers attributed to a single Partner is reviewed. Where the pattern indicates transactions created to generate commission, commissions are reversed in full and the account is suspended under the Partner Program Terms.

## Cancellations

A cancellation ends future qualifying revenue for that customer. It does not reverse commission already earned on revenue that was billed, retained and not refunded.
`;

const earningsDisclaimer = `
## Earnings disclaimer

AI Business Works makes no representation, promise or guarantee about the income any Partner will earn.

Every rate, duration, example and total published on this site describes the structure of the compensation plan. Figures shown in the commission simulator and in worked examples are arithmetic illustrations based on assumptions you or we select - a subscription price, a number of customers, a retention period. They are not forecasts, they are not typical results, and they are not a prediction of your outcome.

Commissions depend on qualifying customer revenue. Qualifying customer revenue depends on whether businesses you introduce subscribe, what they subscribe to, what they pay after any discount, and how long they stay. Many Partners will refer no customers and earn nothing.

AI Business Works does not publish average or typical Partner earnings, and no Partner or representative is authorised to promise you an income.

Participation, eligibility, commissions, customer discounts, Leadership Override and payout terms are subject to the official AI Business Works Partner Program Terms.
`;

export const LEGAL_DOCUMENTS: LegalDocument[] = [
  {
    key: "partner-terms",
    title: "Partner Program Terms",
    summary: "The agreement between AI Business Works and a Partner.",
    bodyMarkdown: partnerTerms.trim(),
  },
  {
    key: "privacy",
    title: "Privacy Policy",
    summary: "What the Partner platform collects, why, and what you can ask for.",
    bodyMarkdown: privacyPolicy.trim(),
  },
  {
    key: "marketing-guidelines",
    title: "Partner Marketing Guidelines",
    summary: "What a Partner may and may not say in public.",
    bodyMarkdown: marketingGuidelines.trim(),
  },
  {
    key: "commission-policy",
    title: "Commission Policy",
    summary: "How commissions are calculated, approved, paid and reversed.",
    bodyMarkdown: commissionPolicy.trim(),
  },
  {
    key: "refund-chargeback-policy",
    title: "Refund and Chargeback Policy",
    summary: "What a refund or chargeback means for Partner compensation.",
    bodyMarkdown: refundPolicy.trim(),
  },
  {
    key: "earnings-disclaimer",
    title: "Earnings Disclaimer",
    summary: "No income is promised, and no figure on this site is a forecast.",
    bodyMarkdown: earningsDisclaimer.trim(),
  },
];

export function legalDocumentByKey(key: string): LegalDocument | undefined {
  return LEGAL_DOCUMENTS.find((d) => d.key === key);
}
