import { createTranslator } from "@leadsmart/i18n";

import { DEFAULT_LOCALE, SUPPORTED_LOCALES, resources } from "./config";

/**
 * A translator for an EXPLICIT locale.
 *
 * `getServerT()` covers the common case — translate for whoever is asking —
 * by reading the locale off the request. Some copy has no request behind it.
 * The weekly newsletter is generated by a cron and sent to an address, so its
 * language comes from the digest row being rendered, not from a cookie nobody
 * set.
 *
 * Deliberately synchronous and free of `server-only`: the bundles are static
 * imports, and the newsletter's email renderer is a pure function that has to
 * stay unit-testable. The resolution order itself lives in the shared package.
 */
export const translatorFor = createTranslator({
  resources,
  defaultLocale: DEFAULT_LOCALE,
  supported: SUPPORTED_LOCALES,
});
