import { resolveLocale } from "@leadsmart/i18n";

import { DEFAULT_LOCALE, resources, type SupportedLocale } from "./config";
import { interpolate, resolveKey } from "./resolveKey";

/**
 * A translator for an EXPLICIT locale.
 *
 * `getServerT()` covers the common case — translate for whoever is asking —
 * by reading the locale off the request. Some copy has no request behind it.
 * The weekly newsletter is generated by a cron and sent to an address, so its
 * language comes from the digest row being rendered, not from a cookie nobody
 * set.
 *
 * Deliberately synchronous and free of `server-only`: the bundles are static
 * imports, and the newsletter's email renderer is a pure function that has to
 * stay unit-testable.
 */
export function translatorFor(
  locale: string | null | undefined,
  defaultNs = "common",
): (key: string, opts?: { ns?: string; [k: string]: unknown }) => string {
  const loc: SupportedLocale = resolveLocale(locale) ?? DEFAULT_LOCALE;
  return (key, opts) => {
    const ns = (opts?.ns as string | undefined) ?? defaultNs;
    type Ns = keyof (typeof resources)[typeof loc];

    const resolved = resolveKey(key, {
      bundle: resources[loc]?.[ns as Ns],
      // Undefined when we're already on English — nothing to fall back to.
      fallbackBundle:
        loc === DEFAULT_LOCALE ? undefined : resources[DEFAULT_LOCALE]?.[ns as Ns],
      defaultValue: opts?.defaultValue,
    });

    // Null means no bundle in any language has it: render the key, loudly.
    return resolved == null ? key : interpolate(resolved, opts ?? {});
  };
}
