import { intlLocale } from "./intl";
import { ALL_LOCALES, resolveLocale, type Locale } from "./locales";
import { interpolate, resolveKey, type Bundle } from "./resolveKey";

/** `resources[locale][namespace]` — the shape every app's config builds. */
export type Resources = Record<string, Record<string, Bundle>>;

export type TranslateOptions = { ns?: string; [k: string]: unknown };
export type Translate = (key: string, opts?: TranslateOptions) => string;

export type TranslatorConfig<L extends Locale> = {
  resources: Resources;
  defaultLocale: L;
  /** The locales this app ships bundles for. Defaults to every known locale. */
  supported?: readonly L[];
};

/**
 * Build `translatorFor(locale, defaultNs)` for one app's resources.
 *
 * A translator for an EXPLICIT locale. `getServerT()` covers the common case —
 * translate for whoever is asking — by reading the locale off the request.
 * Some copy has no request behind it: a weekly digest is generated by a cron
 * and sent to an address, so its language comes from the recipient's stored
 * preference, not from a cookie nobody set.
 *
 * Deliberately synchronous and free of `server-only`: the bundles are static
 * imports, and an email renderer is a pure function that has to stay
 * unit-testable.
 */
export function createTranslator<L extends Locale>(config: TranslatorConfig<L>) {
  const supported = (config.supported ?? ALL_LOCALES) as readonly L[];

  return function translatorFor(
    locale: string | null | undefined,
    defaultNs = "common",
  ): Translate {
    const loc: L = resolveLocale(locale, supported) ?? config.defaultLocale;
    const pluralTag = intlLocale(loc);
    return (key, opts) => {
      const ns = (opts?.ns as string | undefined) ?? defaultNs;

      const resolved = resolveKey(key, {
        bundle: config.resources[loc]?.[ns],
        // Undefined when we're already on the default — nothing to fall back to.
        fallbackBundle:
          loc === config.defaultLocale ? undefined : config.resources[config.defaultLocale]?.[ns],
        defaultValue: opts?.defaultValue,
        count: opts?.count,
        pluralTag,
      });

      // Null means no bundle in any language has it: render the key, loudly.
      return resolved == null ? key : interpolate(resolved, opts ?? {});
    };
  };
}
